export const SITE_NAME = "Artifacts";

export const DEFAULT_DESCRIPTION =
  "Upload, preview, and share self-contained HTML artifacts generated by AI agents.";

export const pageTitle = (page: string) => `${page} | ${SITE_NAME}`;

export const HOME_PAGE_TITLE = "Artifacts | Share agent generated artifacts";

export const ARTIFACTS_PAGE_TITLE = pageTitle("Your artifacts");

interface PageHeadOptions {
  title: string;
  description?: string;
}

export const artifactPageHead = ({
  author,
  name,
  shared = false,
}: {
  author?: string;
  name: string;
  shared?: boolean;
}) => {
  const title = pageTitle(name);
  const description = shared
    ? `View the shared "${name}" artifact${author ? `by ${author}.` : "."}`
    : `Preview and share the "${name}" artifact.`;

  return createPageHead({
    description,
    title,
  });
};

export const createPageHead = ({ title, description }: PageHeadOptions) => ({
  meta: [
    { title },
    ...(description ? [{ content: description, name: "description" }] : []),
    { content: title, property: "og:title" },
    ...(description
      ? [{ content: description, property: "og:description" }]
      : []),
    { content: SITE_NAME, property: "og:site_name" },
    { content: "summary", name: "twitter:card" },
    { content: title, name: "twitter:title" },
    ...(description
      ? [{ content: description, name: "twitter:description" }]
      : []),
  ],
});
