export const SITE_NAME = "Artifacts";

export const DEFAULT_DESCRIPTION =
  "Upload, preview, and share self-contained HTML artifacts generated by AI agents.";

export const pageTitle = (page: string) => `${page} | ${SITE_NAME}`;

export const HOME_PAGE_TITLE = "Artifacts | Share agent generated artifacts";

export const ARTIFACTS_PAGE_TITLE = pageTitle("Your artifacts");

export const SETTINGS_PAGE_TITLE = pageTitle("Settings");

interface PageHeadOptions {
  title: string;
  description?: string;
  image?: string | null;
}

export const artifactPageHead = ({
  author,
  image,
  name,
  shared = false,
}: {
  author?: string;
  image?: string | null;
  name: string;
  shared?: boolean;
}) => {
  const title = pageTitle(name);
  const description = shared
    ? `View the shared "${name}" artifact${author ? `by ${author}.` : "."}`
    : `Preview and share the "${name}" artifact.`;

  return createPageHead({
    description,
    ...(image ? { image } : {}),
    title,
  });
};

export const createPageHead = ({
  title,
  description,
  image,
}: PageHeadOptions) => ({
  meta: [
    { title },
    ...(description ? [{ content: description, name: "description" }] : []),
    { content: title, property: "og:title" },
    ...(description
      ? [{ content: description, property: "og:description" }]
      : []),
    { content: SITE_NAME, property: "og:site_name" },
    ...(image ? [{ content: image, property: "og:image" }] : []),
    {
      content: image ? "summary_large_image" : "summary",
      name: "twitter:card",
    },
    { content: title, name: "twitter:title" },
    ...(description
      ? [{ content: description, name: "twitter:description" }]
      : []),
    ...(image ? [{ content: image, name: "twitter:image" }] : []),
  ],
});
