export const SITE_NAME = "Artifacts";

export const DEFAULT_DESCRIPTION =
  "Upload, preview, and share self-contained HTML artifacts generated by AI agents.";

export const pageTitle = (page: string) => `${page} | ${SITE_NAME}`;

export const HOME_PAGE_TITLE = "Artifacts | Share agent generated artifacts";

export const ARTIFACTS_PAGE_TITLE = pageTitle("Your artifacts");

interface PageHeadOptions {
  title: string;
  description?: string;
}

export const artifactPageHead = ({
  author,
  name,
  shared = false,
}: {
  author?: string;
  name: string;
  shared?: boolean;
}) => {
  const title = pageTitle(name);
  const description = shared
    ? author
      ? `View the shared "${name}" artifact by ${author}.`
      : `View the shared "${name}" artifact.`
    : `Preview and share the "${name}" artifact.`;

  return createPageHead({
    description,
    title,
  });
};

export const createPageHead = ({ title, description }: PageHeadOptions) => ({
  meta: [
    { title },
    ...(description ? [{ name: "description", content: description }] : []),
    { property: "og:title", content: title },
    ...(description
      ? [{ property: "og:description", content: description }]
      : []),
    { property: "og:site_name", content: SITE_NAME },
    { name: "twitter:card", content: "summary" },
    { name: "twitter:title", content: title },
    ...(description
      ? [{ name: "twitter:description", content: description }]
      : []),
  ],
});
